# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build
        run: |
          npm install
          npx browserslist --update-db
          CI= npm run build
      # Runs a set of commands using the runners shell
      - name: firebase deploy
        run: |
          sudo npm install -g firebase-tools --unsafe-perm=true --allow-root
          firebase use default
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
